// fetch posts
export const STARTED_FETCH_POSTS = 'STARTED_FETCH_POSTS';
export const FINISHED_FETCH_POSTS = 'FINISHED_FETCH_POSTS';
export const ERROR_FETCH_POSTS = 'ERROR_FETCH_POSTS';

// fetch user data
export const STARTED_FETCH_USER_DATA = 'STARTED_FETCH_USER_DATA';
export const FINISHED_FETCH_USER_DATA = 'FINISHED_FETCH_USER_DATA';
export const ERROR_FETCH_USER_DATA = 'ERROR_FETCH_USER_DATA';

// fetch comments
export const STARTED_FETCH_COMMENTS = 'STARTED_FETCH_COMMENTS';
export const FINISHED_FETCH_COMMENTS = 'FINISHED_FETCH_COMMENTS';
export const ERROR_FETCH_COMMENTS = 'ERROR_FETCH_COMMENTS';

// fetch post
export const STARTED_FETCH_POST = 'STARTED_FETCH_POST';
export const FINISHED_FETCH_POST = 'FINISHED_FETCH_POST';
export const ERROR_FETCH_POST = 'ERROR_FETCH_POST';

export const SWIPE_UPDATE_POSTS = 'UPDATE_POSTS';
export const DELETE_ALL_POSTS = 'DELETE_ALL_POSTS';
export const CLEAN_SELECTED_POST = 'CLEAN_SELECTED_POST';
