// fetch posts
export const STARTED_FETCH_POSTS = 'STARTED_FETCH_POSTS';
export const FINISHED_FETCH_POSTS = 'FINISHED_FETCH_POSTS';
export const ERROR_FETCH_POSTS = 'ERROR_FETCH_POSTS';

export const SWIPE_UPDATE_POSTS = 'UPDATE_POSTS';
export const DELETE_ALL_POSTS = 'DELETE_ALL_POSTS';
